# Generated by Django 5.2.5 on 2025-10-02 00:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('unidad', models.CharField(choices=[('UN', 'Unidad'), ('KG', 'Kilogramo'), ('LT', 'Litro')], default='UN', max_length=2, verbose_name='Unidad')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio')),
                ('stock_minimo', models.PositiveIntegerField(default=10, verbose_name='Stock mínimo')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, verbose_name='Código de lote')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('fecha_vencimiento', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de vencimiento')),
                ('ubicacion', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lote',
                'ordering': ['fecha_vencimiento', 'codigo'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'codigo'), name='uq_lote_producto_codigo')],
            },
        ),
    ]
