# Generated by Django 5.2.5 on 2025-10-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=90, unique=True, verbose_name='Nombre de Producto'),
        ),
    ]
