# Generated by Django 5.2.5 on 2025-10-07 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='telefono',
        ),
        migrations.AddField(
            model_name='contacto',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
