# Generated by Django 5.2.5 on 2025-10-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_remove_contacto_email_remove_contacto_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='usuario',
        ),
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
